{% set name = "XStatic-Font-Awesome" %}
{% set version = "6.2.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/XStatic-Font-Awesome-{{ version }}.tar.gz
  sha256: f075871096128638f2e1539020d8227754c3d885dd68e7ee6de9a01235076828

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - python >=3.7
    - pip
    - setuptools
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - xstatic.pkg.font_awesome

about:
  home: https://github.com/FortAwesome/Font-Awesome
  summary: Font-Awesome 6.2.1 (XStatic packaging standard)
  license: CC-BY-4.0 AND OFL-1.1 AND MIT
  license_file:
    - xstatic/pkg/font_awesome/data/LICENSE.txt

extra:
  recipe-maintainers:
    - ReimarBauer
